
# size of landscape
ROWS = 50
COLUMNS = 50

# parameters for individuals
INIT_NUMBER_GRASS = 1300
INIT_NUMBER_SHEEP = 100
INIT_NUMBER_WOLVES = 50

#INIT_ENERGY_SHEEP = 5
#INIT_ENERGY_WOLF = 5
IND_MAX_ENERGY = 10

P_REPRODUCE_SHEEP = 0.04
P_REPRODUCE_WOLF = 0.05

SHEEP_GAIN_FROM_FOOD = 4
WOLF_GAIN_FROM_FOOD  = 20

GRASS_REGROWTH_TIME = 30
