
# size of landscape
ROWS = 5
COLUMNS = 5

# parameters for individuals
INIT_NUMBER_SHEEP = 5
INIT_NUMBER_WOLVES = 5

INIT_ENERGY_SHEEP = 5
INIT_ENERGY_WOLF = 5

P_REPRODUCE_SHEEP = 0.1
P_REPRODUCE_WOLF = 0.1

SHEEP_GAIN_FROM_FOOD = 4
WOLF_GAIN_FROM_FOOD  = 4
